# Generated by Django 5.0.4 on 2024-05-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_contactinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка')),
                ('content', models.TextField(blank=True, null=True, verbose_name='текст')),
                ('photo', models.ImageField(upload_to='product/img')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='дата создания')),
                ('published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('view_counter', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
            },
        ),
    ]
