# Generated by Django 5.0.4 on 2024-05-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_version_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='error_message',
            field=models.CharField(blank=True, max_length=38, null=True, verbose_name='может быть только одна активная версия'),
        ),
    ]
