# Generated by Django 4.2.2 on 2024-06-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_blog_article_owner_product_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_category', 'can change category'), ('can_edit_description', 'can change description')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
